# movie-chart/templates/service-db.yaml
apiVersion: v1
kind: Service
metadata:
  name: movie-db
spec:
  ports:
  - port: {{ .Values.service_db.port }}
    targetPort: {{ .Values.service_db.targetport }}
  selector:
    app: movie-db
