# cast-chart/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cast-db
spec:
  serviceName: "cast-db"
  replicas: 1
  selector:
    matchLabels:
      app: cast-db
  template:
    metadata:
      labels:
        app: cast-db
    spec:
      containers:
        - name: cast-db
          image: postgres:12.1-alpine
          env:
            - name: POSTGRES_USER
              value: "{{ .Values.statefulset.env.POSTGRES_USER }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.statefulset.env.POSTGRES_PASSWORD }}"
            - name: POSTGRES_DB
              value: "{{ .Values.statefulset.env.POSTGRES_DB }}"
            - name: PGDATA
              value: "{{ .Values.statefulset.env.PGDATA }}"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: cast-db-data
              mountPath: "{{ .Values.statefulset.volumeMounts.mountPath }}"
  volumeClaimTemplates:
    - metadata:
        name: cast-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

