apiVersion: v1
kind: Service
metadata:
  name: movie-service
spec:
  type: NodePort
  ports:
  - name: "8001"
    port: 8001
    targetPort: 8000
    nodePort: 31023
  selector:
    app: movie-service

